version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: setel-order-mysql
    command: --init-file /data/application/init.sql
    ports:
        - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'dummy'
      MYSQL_PASSWORD: 'dummy'
    volumes:
      - ./.docker/mysql/init.sql:/data/application/init.sql
      - ./.docker/mysql/vol:/var/lib/mysql
#     networks:
#       - setelnetwork
# networks:
#   setelnetwork: